base_config:
  - ../sr_base.yaml
  - ../df2k4x.yaml
trainer_cls: tasks.highresnet_ltae.HighResNetLTAETrainer
# model
hidden_size: 64
lr: 0.0007
num_block: 17

# added by @hubert
test_diff: false
save_intermediate: false
# train and eval
max_updates: 4 # 400000
batch_size: 5
eval_batch_size: 5
test_batch_size: 1
val_check_interval:  4 # 30000
save_ckpt_interval:  4 # 20000
train_diffsr: false
max_s2_images: 8
misr_ref_image: closest

